### PR TITLE
added MAX_RAW_SIZE for node12 template

### PR DESCRIPTION
**Pull request by fundef1**
FIXES: #PR246

## Motivation and Context
- [x] I have raised an issue to propose this change ([required]

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by alexellis** [comment]
@fundef1 please take a moment to fill out the whole PR template, and then we will review. You should also link to the issue in the motivation section with  i.e. `Fixes #NUMBER` 

https://raw.githubusercontent.com/openfaas/docs/master/.github/PULL_REQUEST_TEMPLATE.md

Thank you for being a good open source citizen.

**Comment by fundef1** [comment]
@alexellis how can i do the sign-off thing via the github's web UI?

**Comment by alexellis** [comment]
It's explained in the contribution guide, but I would recommend that you run the one simple command that Derek has given you instead.

**Comment by alexellis** [comment]
Not to worry. Perhaps if you are not happy to use the git CLI in the future, you could propose the changes you want and wait for us to triage and work on them?

**Comment by fundef1** [comment]
Sure, and btw it's not that I don't kike the git CLI altogether. For documentation I do prefer the github site, for code the CLI makes more sense.

**Pull request closed without merging**
