### PR TITLE
Add documentation describing the imagePullPolicy

### LINKED ISSUE #14: Document how to use image pull policy for faas-netes
This still needs to be done, opening so I don't lose track of it.

### PR DESCRIPTION
**Pull request by LucasRoesler**
**What**
- Adds a reference page for the `faas-netes` image pull policy configuration

Closes #14

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @LucasRoesler this looks like good content, but I think it may be better in a sub-section of the Kubernetes deployment guide since it doesn't apply to Swarm or other back-ends.

**Comment by LucasRoesler** [comment]
I just moved the content into the k8s deployment documentation and I lightly reorganized the sectioning because I think it had gotten broken earlier

**Comment by alexellis** [comment]
LGTM but has a merge conflict @LucasRoesler - please rebase.

**Comment by LucasRoesler** [comment]
Just pushed the rebase

**Comment by alexellis** [comment]
Thanks. For future reference please make headers active rather than gerunds. "install" vs. "installing" - customize vs customizing.

**Comment by alexellis** [comment]
Can you also comment on why the numbers were removed?

**Comment by alexellis** [comment]
Noticed some typos and also that you didn't remove the numbers consistently?

> If you'd like to use helm follow the instructions in 2.0a and then come back here, otherwise follow 2.0b to use plain `kubectl`.

**Comment by alexellis** [comment]
I'm fixing this up along with some other items..

**Pull request merged**
