### PR TITLE
Fixes cURL command header

### PR DESCRIPTION
**Pull request by Miserlou**
"Fix" for https://github.com/openfaas/docs/issues/175

### CODE REVIEW

**Comment by viveksyngh** [comment]
@Miserlou Please signoff your commit with `git commit --amend --signoff` and force push the changes. 

Changes looks fine to me.

**Comment by alexellis** [comment]
I think Rich said that "this is still not right". Do we know why?

**Comment by viveksyngh** [comment]
For that I have commented on the issue for this PR. #176

**Comment by alexellis** [comment]
You just need to sign-off your commit now @Miserlou, before we can merge.

Follow the instructions given by Derek please. Ask on Slack in #contributors if you could use any additional help with that.

**Pull request closed without merging**
