### PR TITLE
Update table with available NodeJS templates

### PR DESCRIPTION
**Pull request by welteki**
## Description

Add the latest node18 template to the table and update the `supported` status.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Keep the NodeJS template docs up to date with the latest changes.

## How Has This Been Tested?

Verified the table is displayed correctly.

Screenshot 2023-03-15 at 17 17 41

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by alexellis** [comment]
We don't have node17 in the screenshot and can probably delete anything prior to that?

Could you update it please?

**Comment by welteki** [comment]
> We don't have node17 in the screenshot and can probably delete anything prior to that?

Node 17 is not an LTS version and is not supported by nodejs.org anymore.

**Comment by welteki** [comment]
16 is still supported in maintenance.

Do we remove the unsupported version and just keep 16 and 18 or add all version and indicate which ones are not supported anymore?

**Comment by alexellis** [comment]
Thanks

**Pull request merged**
