### PR TITLE
[WIP] Add cors reference

### PR DESCRIPTION
**Pull request by kenfdev**
This is an initial draft explaining how to deal with CORS when developing web apps locally.
You'll have to run `docker run --rm -it -p 8000:8000 -v `pwd`:/docs squidfunk/mkdocs-material` in order to make the images appear (I needed to center them inside the markdown).

I'd greatly appreciate feedback and how this page should be. (I placed it inside `references` )

I'm going to squash the commits at the end.

Related issue:  #22 

Here's a capture in case you don't have time to `docker run`.

cors openfaas

### CODE REVIEW

**Comment by affix** [comment]
@kenfdev as mentioned on slack it would be worth talking about how to add the CORS header to your function

**Comment by kenfdev** [comment]
@affix Thanks for the feedback. Yes, currently this page only explains how you could avoid `CORS` and not about doing `CORS`.  I'll try adding another section about `CORS`.

**Comment by kenfdev** [comment]
Actually, to make `CORS` work with headers, we'll need webpack **and** the function to at least return `Access-Control-Allow-Origin` for it to work. This isn't possible with the default watchdog afaik. I've confirmed it's working with the `of-watchdog` by creating a function like this ( `Access-Control-Allow-Credentials` isn't mandatory) :

```js
module.exports = (event, context) => {
   let err;
   const result = JSON.stringify(event.body);
   const headers = {
     'Access-Control-Allow-Origin': '*',
     'Access-Control-Allow-Credentials': true
   };

   context
     .status(200)
     .headers(headers)
     .succeed(result);
 };
```

I think it's going to become a bit too much for this page. WDYT @alexellis @affix

**Comment by alexellis** [comment]
I will have to catch up with this next week. Ken what is your gut feeling for this?

**Comment by alexellis** [comment]
Let's get this in, feel free to make follow-up changes in-flight.

Thanks for the work Ken.

Alex

**Pull request merged**
