### PR TITLE
Bump the cert-manager version in the docs

### PR DESCRIPTION
**Pull request by inteon**
## Description

cert-manager v1.3.1 has been EOL for a long time: https://cert-manager.io/docs/releases/

### CODE REVIEW

**Comment by alexellis** [comment]
@welteki please can you send a PR for this change as I'm not sure that @inteon is going to sign this off, and it seems like something we should get in immediately?

**Comment by inteon** [comment]
@alexellis it would indeed be easier if you or @welteki create a PR instead.
Thanks for the help!

**Comment by alexellis** [comment]
No problems. That is what our contributing guide suggests anyway.

**Comment by alexellis** [comment]
Are you considering using a version of OpenFaaS for a project?

**Pull request closed without merging**
