### PR TITLE
Add simple cron job reference walkthrough

### PR DESCRIPTION
**Pull request by LucasRoesler**
**What**
- Documents a very simple cronjob example in kubernetes
- Includes a comment about modifying the example for multiple
namespaces
- Includes a comment about handling basic auth
- A demo repo is available at https://github.com/LucasRoesler/openfaas-cron-demo

**Why**
Closes openfaas/faas#719

### CODE REVIEW

**Comment by LucasRoesler** [comment]
One thing that I noticed, I could not find a good reference or walk-through of the basic auth setup/configuration . That would be a nice document to be able to reference from this one.

**Comment by alexellis** [comment]
LGTM, thank you Lucas. Did you test with the docker run instruction? When I merge it does straight to master

**Comment by LucasRoesler** [comment]
I tested the whole thing with the demo repo on a gke cluster. Each of the shell cmds and output are copied direct from my test of th docs

**Comment by alexellis** [comment]
When I said testing here I meant did you run the docker preview site locally?

**Comment by LucasRoesler** [comment]
Sorry, no I hadn't done that

**Comment by alexellis** [comment]
Best to do that now and check it compiles and looks as expected.

**Comment by LucasRoesler** [comment]
everything looks good 👍

**Pull request merged**
