### PR TITLE
Fix TLS script

### PR DESCRIPTION
**Pull request by ivoreis**
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by ivoreis** [comment]
After reading the contributing guide I've raised this issue: https://github.com/openfaas/docs/issues/150

**Comment by alexellis** [comment]
Thanks for your PR.

@lucasroesler PTAL

**Comment by alexellis** [comment]
By the way, you can keep your pull request open. You just need to follow the instructions given by the bot.

**Comment by ivoreis** [comment]
Thanks, @alexellis. Closed in favour of https://github.com/openfaas/docs/pull/151

**Pull request closed without merging**
