### PR TITLE
Add metrics reference page with examples

### LINKED ISSUE #95: Document the gateway and function metrics
The gateway currently exposes prometheus metrics that users may be interested in.  We should document these metrics and perhaps some of the common queries they would want to use.

### PR DESCRIPTION
**Pull request by LucasRoesler**
**What**
- Add reference documentation for the metrics exposed by the gateway
- Include examples for the usage of those metrics

Resolves #95

### CODE REVIEW

**Comment by rgee0** [comment]
Should we include an example which shows how to focus a query on a particular function?

**Comment by alexellis** [comment]
I was thinking of having this page under the architecture section and linking from the gateway page as part of this PR?

**Comment by LucasRoesler** [comment]
@rgee0 i added an example as you described

**Comment by LucasRoesler** [comment]
@alexellis I put it in Reference because I figure that the behavior and performance of the functions would be of general interest

**Pull request merged**
