### PR TITLE
Extention docs

### PR DESCRIPTION
**Pull request by cpitkin**
Added the documentation extensions reference in the README

### CODE REVIEW

**Comment by alexellis** [comment]
Hi what does `Extention docs` mean?

**Comment by alexellis** [comment]
Derek add label: no-dco

**Comment by alexellis** [comment]
It'd be great if we could get a bit more of a descriptive pull request and also the commits need to be signed-off like with the main project. Derek will remove the no-dco label when you have that fixed up.

It may be simple to reset your changes, stash them and then apply them to origin/master so it's all fresh without the "remote branch merge" in the history.

**Comment by cpitkin** [comment]
I see I need to clean up my master branch for sure. I will start to get in a better habit of descriptive PR messages. Being my first contributions to open source it is taking me a bit to find the correct workflow. I have never signed commits before so we'll see how this goes. I am pretty sure [this](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work) is what you mean.

Thanks for the help!

**Comment by alexellis** [comment]
The contribution guide in the main faas repo has an explanation on contributing for the first time as well as details about commit messages and signing. I'm glad you're helping us out so don't mind going over this stuff.

**Pull request closed without merging**
