### PR TITLE
[Typo] Key file name in secret create command was wrong

### PR DESCRIPTION
**Pull request by kevin-lindsay-1**
## Description

Typo.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by kevin-lindsay-1** [comment]
I made this commit via the GH UI. Probably can't sign it.

**Comment by alexellis** [comment]
Thanks for the feedback on these instructions.

This is just a sign-off message, so you can paste it into your commit message when you do the patch in the UI.

We could also add that leaving blank or setting to "localhost" for the public_domain is a viable option. cc @welteki

**Comment by welteki** [comment]
> We could also add that leaving blank or setting to "localhost" for the public_domain is a viable option. cc @welteki

Yes, this works of you just want to access the dashboard locally. Do you want me to open separate PR for this addition?

**Comment by alexellis** [comment]
Please :+1:

**Comment by welteki** [comment]
Superseded by  #285

**Comment by alexellis** [comment]
Thanks @kevin-lindsay-1 - feedback taken on board in #285

**Pull request closed without merging**
