### PR TITLE
Add k8s DNS troubleshooting docs

### PR DESCRIPTION
**Pull request by gabeduke**
## Description
This issue came up in a slack thread. This PR documents the solution for
reference.

My IDE auto corrected some markdown formatting elsewhere in the file. I can revert these changes if it competes with a repository linter.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by LucasRoesler** [comment]
@gabeduke I like the new addition, but for simplicity and to ensure we don't end up with a formatting battle between editors, can you revert the formatting changes?

I know it isn't fun to revert those kind of changes, I run into a similar issue when I edit these files too. But, the new section looks good and I would love to see it merged in

**Comment by gabeduke** [comment]
@LucasRoesler It's no trouble, I just pushed an update.

**Comment by LucasRoesler** [comment]
Thanks @gabeduke  and sorry it took me awhile to respond, I've been sick the last couple of days and essentially off my computer.

**Comment by LucasRoesler** [comment]
@alexellis or @burtonr do you want to give it a second look?

**Comment by gabeduke** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
