### PR TITLE
Document the new faas-cli --tag feature

### PR DESCRIPTION
**Pull request by mrtind**
Add to cli field in file build.md explanation to what the --tag
feature does.

Signed-off-by: Martin Dekov (VMware) <mdekov@vmware.com>

### CODE REVIEW

**Comment by mrtind** [comment]
This PR references issue https://github.com/openfaas/docs/issues/49.

**Comment by alexellis** [comment]
The outline looks good, but the ask was for this to be covered for all the sub-commands (push,build,deploy) in some generic way. Do you think it deserves its own sub-page?

**Comment by alexellis** [comment]
Referring to #49:

> Remember this covers build/push and deploy - do we really want to duplicate the text in each part - or could it be a sub-page of the CLI heading?

**Comment by alexellis** [comment]
I've written this up in a dedicated page, but we may want to make some small references in each page or section on build/deploy/push back to the tagging feature.

**Pull request closed without merging**
