### PR TITLE
Upgrade docs for kubernetes and cert-manager, closes #185

### LINKED ISSUE #185: Update docs to use cert-manager 0.11.0
## Proposed change

Update docs to use cert-manager 0.11.0 to keep up to date.

https://docs.cert-manager.io/en/release-0.11/

## Context

This version has breaking changes in the annotations used and how issuers work.

## Your Environment

Kubernetes 1.15 / 1.16

See how with [Upgrading from v0.10 to v0.11](https://docs.cert-manager.io/en/release-0.11/tasks/upgrading/upgrading-0.10-0.11.html)

### PR DESCRIPTION
**Pull request by Waterdrips**
Signed-off-by: Alistair Hey <alistair.hey@gmail.com>
Closes #185 

## Description

Update docs for kubernetes with cert-manager to the 0.11 syntax
## Motivation and Context

- [x] I have raised an issue to propose this change ([required] #185 (https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
New Kubernetes cluster (civo cloud) installed using the updated guide command by command and verify the output.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by alexellis** [comment]
I see a typo kubetneres

Thanks for the PR

**Comment by Waterdrips** [comment]
Updated commit message 👍 thanks.

**Comment by alexellis** [comment]
PR'ing like a pro @Waterdrips, thank you 💪 

Great commit message too.

**Comment by alexellis** [comment]
Next up, if you can help is https://github.com/openfaas-incubator/ofc-bootstrap/issues/138

It has a little more code to change including some Go, but is the same principle.

**Pull request merged**
