### PR TITLE
Add Bulletproof logo

### PR DESCRIPTION
**Pull request by ivanayov**
This adds Bulletproof logo to the Users of OpenFaaS

Signed-off-by: Ivana Yovcheva (VMware) <iyovcheva@vmware.com>

[faas#776](https://github.com/openfaas/faas/issues/776#issuecomment-422812924)

screen shot 2018-09-19 at 19 31 32

### CODE REVIEW

**Comment by alexellis** [comment]
This doesn't appear to be in alphabetical order like the others? Please could you amend?

**Comment by ivanayov** [comment]
@alexellis It's updated now

**Comment by alexellis** [comment]
Could we use the original logo asset provided in PNG format by the user? I didn't expect you to convert to an SVG.

**Comment by ivanayov** [comment]
@alexellis changed to the original

**Pull request merged**
